"""empty message

Revision ID: 58f12c9da16f
Revises: a0a2739caebd
Create Date: 2025-06-25 18:44:26.270854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f12c9da16f'
down_revision = 'a0a2739caebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('used_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('earned_points', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_orders_referrer_id'), ['referrer_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['referrer_id'], ['id'])

    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('user_addresses_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_cards', schema=None) as batch_op:
        batch_op.drop_constraint('user_cards_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('points_balance', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_column('points_balance')
        batch_op.drop_column('referral_code')

    with op.batch_alter_table('user_cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_cards_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_addresses_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_referrer_id'))
        batch_op.drop_column('earned_points')
        batch_op.drop_column('used_points')
        batch_op.drop_column('referrer_id')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
