"""Обновление Product и ProductImage

Revision ID: a0a2739caebd
Revises: 0e53fa830b92
Create Date: 2025-06-22 22:15:30.338972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a2739caebd'
down_revision = '0e53fa830b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=20), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('size')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
